[package]
name = "confini"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_core = "0.5.1"
rust-ini = "0.15"
clap = "~2.27.0"
rust-crypto = "0.2"
base64 = "0.12.3"
ctrlc = "3.1.7"